name: Build iOS Framework

on:
  push:
    branches:
      - main  # Adjust the branch name as per your needs

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build iphoneos
        run: |
          rm -rf build
          xcodebuild archive \
            -scheme CalendarControl \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath './build/CalendarControl.framework-iphoneos.xcarchive' \
            SKIP_INSTALL=NO \
            BUILD_LIBRARIES_FOR_DISTRIBUTION=YES
            
      - name: Build iphonesimulator
        run: |
          xcodebuild archive \
            -scheme CalendarControl \
            -configuration Release \
            -destination 'generic/platform=iOS Simulator' \
            -archivePath './build/CalendarControl.framework-iphonesimulator.xcarchive' \
            SKIP_INSTALL=NO \
            BUILD_LIBRARIES_FOR_DISTRIBUTION=YES

      - name: Build iOS Framework
        run: |
          xcodebuild -create-xcframework \
            -framework './build/CalendarControl.framework-iphonesimulator.xcarchive/Products/Library/Frameworks/CalendarControl.framework' \
            -framework './build/CalendarControl.framework-iphoneos.xcarchive/Products/Library/Frameworks/CalendarControl.framework' \
            -output './build/CalendarControl.xcframework'
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: "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"
