name: Build iOS Framework

on:
  push:
    branches:
      - main  # Adjust the branch name as per your needs

permissions:
  contents: write
env:
  SECRET_PERSONAL_TOKEN: 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
  
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build iphoneos
        run: |
          rm -rf build
          xcodebuild archive \
            -scheme CalendarControl \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath './build/CalendarControl.framework-iphoneos.xcarchive' \
            SKIP_INSTALL=NO \
            BUILD_LIBRARIES_FOR_DISTRIBUTION=YES
            
      - name: Build iphonesimulator
        run: |
          xcodebuild archive \
            -scheme CalendarControl \
            -configuration Release \
            -destination 'generic/platform=iOS Simulator' \
            -archivePath './build/CalendarControl.framework-iphonesimulator.xcarchive' \
            SKIP_INSTALL=NO \
            BUILD_LIBRARIES_FOR_DISTRIBUTION=YES

      - name: Build iOS Framework
        run: |
          xcodebuild -create-xcframework \
            -framework './build/CalendarControl.framework-iphonesimulator.xcarchive/Products/Library/Frameworks/CalendarControl.framework' \
            -framework './build/CalendarControl.framework-iphoneos.xcarchive/Products/Library/Frameworks/CalendarControl.framework' \
            -output './build/CalendarControl.xcframework'

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: framework-artifact
          path: build/CalendarControl.xcframework
          
      - name: Commit files
        run: |
          git commit -a -m "Add changes"
          git push  origin main
          
  trigger:
    runs-on: ubuntu-latest
    steps:         
      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: sudhanshublah
          repo: imporved-train
          github_token: ${{ env.SECRET_PERSONAL_TOKEN }}
          wait_workflow: true
          workflow_file_name: main.yml
#       - name: simple-github-auto-push
#       # You may pin to the exact commit or the version.
#       # uses: hisasann/simple-github-auto-push@9b1d9d0ed24c9eb7f9f27c7b0765775804b417a3
#         uses: hisasann/simple-github-auto-push@v0.0.2
#         env:
#           GITHUB_TOKEN: "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"
#           BRANCH_NAME: "main"
