on:
  workflow_run:
    workflows:
      - 'Build iOS Framework'
    types:
      - completed

jobs:
  copy-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2
        with:
          repository: veeraagam/CalendarControl
          ref: ${{ github.event.workflow_run.head_commit.id }}

      - name: Copy Folder to Destination Repository
        run: |
          git clone https://github.com/sudhanshublah/improved-train.git
          
          git config --global user.email "sudhanshuk1219@gmail.com"
          git config --global user.name "sudhanshublah"
          
          mkdir -p improved-train/Sources && cp -r build/CalendarControl.xcframework improved-train/Sources/CalendarControl.xcframework
          cd improved-train && git add . && git commit -m "updated framework" && git push origin main

    
    
    
    
#         # Commit and push changes
#           cd destination
#           git add .
#           git commit -m "Copy framework folder from source repository"
#           git push origin main
