on:
  workflow_run:
    workflows:
      - 'Build iOS Framework'
    types:
      - completed

jobs:
  copy-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2
        with:
          repository: veeraagam/CalendarControl
          ref: ${{ github.event.workflow_run.head_commit.id }}

      - name: Copy to different repo
        uses: nkoppel/push-files-to-another-repository@1.1.1
        env:
          API_TOKEN_GITHUB: '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'
        with:
          source-files: 'build/CalendarControl.xcframework'
#           destination-username: 'sudhanshublah'
          destination-repository: 'sudhanshublah/improved-train'
          destination-directory: 'Sources/'
#           commit-email: 'nathankoppel0@gmail.com'
    
    
    
#         # Commit and push changes
#           cd destination
#           git add .
#           git commit -m "Copy framework folder from source repository"
#           git push origin main
